version: '3.1'

services:
  db:
    container_name: pg-container
    build: db/.docker
    restart: always
    environment:
      POSTGRES_DB: 'nestjs-db'
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
